// Generated by Wrangler

import { R2Bucket } from "@cloudflare/workers-types";

// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  PRIVATE: R2Bucket;
  PUBLIC: R2Bucket;
  BASE_URL: string;
}
