export const BASE_URL =
  import.meta.env.VITE_BASE_URL || "https://www.nuke.engineering";
export const WORKER_URL =
  import.meta.env.VITE_WORKER_BASE_URL || "https://r2.nuke.engineering";

export const COUNTRIES_DATA = [
  {
    name: "Afghanistan",
    phonePrefix: "93",
    emoji: "🇦🇫",
    nationality: "Afghan",
  },
  {
    name: "Albania",
    phonePrefix: "355",
    emoji: "🇦🇱",
    nationality: "Albanian",
  },
  {
    name: "Algeria",
    phonePrefix: "213",
    emoji: "🇩🇿",
    nationality: "Algerian",
  },
  {
    name: "Andorra",
    phonePrefix: "376",
    emoji: "🇦🇩",
    nationality: "Andorran",
  },
  { name: "Angola", phonePrefix: "244", emoji: "🇦🇴", nationality: "Angolan" },
  {
    name: "Antigua and Barbuda",
    phonePrefix: "1-268",
    emoji: "🇦🇬",
    nationality: "Antiguan or Barbudan",
  },
  {
    name: "Argentina",
    phonePrefix: "54",
    emoji: "🇦🇷",
    nationality: "Argentine",
  },
  {
    name: "Armenia",
    phonePrefix: "374",
    emoji: "🇦🇲",
    nationality: "Armenian",
  },
  {
    name: "Australia",
    phonePrefix: "61",
    emoji: "🇦🇺",
    nationality: "Australian",
  },
  { name: "Austria", phonePrefix: "43", emoji: "🇦🇹", nationality: "Austrian" },
  {
    name: "Azerbaijan",
    phonePrefix: "994",
    emoji: "🇦🇿",
    nationality: "Azerbaijani",
  },
  {
    name: "Bahamas",
    phonePrefix: "1-242",
    emoji: "🇧🇸",
    nationality: "Bahamian",
  },
  {
    name: "Bahrain",
    phonePrefix: "973",
    emoji: "🇧🇭",
    nationality: "Bahraini",
  },
  {
    name: "Bangladesh",
    phonePrefix: "880",
    emoji: "🇧🇩",
    nationality: "Bangladeshi",
  },
  {
    name: "Barbados",
    phonePrefix: "1-246",
    emoji: "🇧🇧",
    nationality: "Barbadian",
  },
  {
    name: "Belarus",
    phonePrefix: "375",
    emoji: "🇧🇾",
    nationality: "Belarusian",
  },
  { name: "Belgium", phonePrefix: "32", emoji: "🇧🇪", nationality: "Belgian" },
  { name: "Belize", phonePrefix: "501", emoji: "🇧🇿", nationality: "Belizean" },
  { name: "Benin", phonePrefix: "229", emoji: "🇧🇯", nationality: "Beninese" },
  {
    name: "Bhutan",
    phonePrefix: "975",
    emoji: "🇧🇹",
    nationality: "Bhutanese",
  },
  {
    name: "Bolivia",
    phonePrefix: "591",
    emoji: "🇧🇴",
    nationality: "Bolivian",
  },
  {
    name: "Bosnia and Herzegovina",
    phonePrefix: "387",
    emoji: "🇧🇦",
    nationality: "Bosnian or Herzegovinian",
  },
  {
    name: "Botswana",
    phonePrefix: "267",
    emoji: "🇧🇼",
    nationality: "Botswanan",
  },
  { name: "Brazil", phonePrefix: "55", emoji: "🇧🇷", nationality: "Brazilian" },
  { name: "Brunei", phonePrefix: "673", emoji: "🇧🇳", nationality: "Bruneian" },
  {
    name: "Bulgaria",
    phonePrefix: "359",
    emoji: "🇧🇬",
    nationality: "Bulgarian",
  },
  {
    name: "Burkina Faso",
    phonePrefix: "226",
    emoji: "🇧🇫",
    nationality: "Burkinabe",
  },
  {
    name: "Burundi",
    phonePrefix: "257",
    emoji: "🇧🇮",
    nationality: "Burundian",
  },
  {
    name: "Cambodia",
    phonePrefix: "855",
    emoji: "🇰🇭",
    nationality: "Cambodian",
  },
  {
    name: "Cameroon",
    phonePrefix: "237",
    emoji: "🇨🇲",
    nationality: "Cameroonian",
  },
  { name: "Canada", phonePrefix: "1", emoji: "🇨🇦", nationality: "Canadian" },
  {
    name: "Cape Verde",
    phonePrefix: "238",
    emoji: "🇨🇻",
    nationality: "Cape Verdean",
  },
  {
    name: "Central African Republic",
    phonePrefix: "236",
    emoji: "🇨🇫",
    nationality: "Central African",
  },
  { name: "Chad", phonePrefix: "235", emoji: "🇹🇩", nationality: "Chadian" },
  { name: "Chile", phonePrefix: "56", emoji: "🇨🇱", nationality: "Chilean" },
  { name: "China", phonePrefix: "86", emoji: "🇨🇳", nationality: "Chinese" },
  {
    name: "Colombia",
    phonePrefix: "57",
    emoji: "🇨🇴",
    nationality: "Colombian",
  },
  {
    name: "Comoros",
    phonePrefix: "269",
    emoji: "🇰🇲",
    nationality: "Comorian",
  },
  {
    name: "Congo, Democratic Republic of the",
    phonePrefix: "243",
    emoji: "🇨🇩",
    nationality: "Congolese",
  },
  {
    name: "Congo, Republic of the",
    phonePrefix: "242",
    emoji: "🇨🇬",
    nationality: "Congolese",
  },
  {
    name: "Costa Rica",
    phonePrefix: "506",
    emoji: "🇨🇷",
    nationality: "Costa Rican",
  },
  {
    name: "Croatia",
    phonePrefix: "385",
    emoji: "🇭🇷",
    nationality: "Croatian",
  },
  { name: "Cuba", phonePrefix: "53", emoji: "🇨🇺", nationality: "Cuban" },
  { name: "Cyprus", phonePrefix: "357", emoji: "🇨🇾", nationality: "Cypriot" },
  {
    name: "Czech Republic",
    phonePrefix: "420",
    emoji: "🇨🇿",
    nationality: "Czech",
  },
  { name: "Denmark", phonePrefix: "45", emoji: "🇩🇰", nationality: "Danish" },
  {
    name: "Djibouti",
    phonePrefix: "253",
    emoji: "🇩🇯",
    nationality: "Djiboutian",
  },
  {
    name: "Dominica",
    phonePrefix: "1-767",
    emoji: "🇩🇲",
    nationality: "Dominican",
  },
  {
    name: "Dominican Republic",
    phonePrefix: "1-809, 1-829, 1-849",
    emoji: "🇩🇴",
    nationality: "Dominican",
  },
  {
    name: "East Timor",
    phonePrefix: "670",
    emoji: "🇹🇱",
    nationality: "Timorese",
  },
  {
    name: "Ecuador",
    phonePrefix: "593",
    emoji: "🇪🇨",
    nationality: "Ecuadorian",
  },
  { name: "Egypt", phonePrefix: "20", emoji: "🇪🇬", nationality: "Egyptian" },
  {
    name: "El Salvador",
    phonePrefix: "503",
    emoji: "🇸🇻",
    nationality: "Salvadoran",
  },
  {
    name: "Equatorial Guinea",
    phonePrefix: "240",
    emoji: "🇬🇶",
    nationality: "Equatorial Guinean",
  },
  {
    name: "Eritrea",
    phonePrefix: "291",
    emoji: "🇪🇷",
    nationality: "Eritrean",
  },
  {
    name: "Estonia",
    phonePrefix: "372",
    emoji: "🇪🇪",
    nationality: "Estonian",
  },
  { name: "Eswatini", phonePrefix: "268", emoji: "🇸🇿", nationality: "Swazi" },
  {
    name: "Ethiopia",
    phonePrefix: "251",
    emoji: "🇪🇹",
    nationality: "Ethiopian",
  },
  { name: "Fiji", phonePrefix: "679", emoji: "🇫🇯", nationality: "Fijian" },
  { name: "Finland", phonePrefix: "358", emoji: "🇫🇮", nationality: "Finnish" },
  { name: "France", phonePrefix: "33", emoji: "🇫🇷", nationality: "French" },
  { name: "Gabon", phonePrefix: "241", emoji: "🇬🇦", nationality: "Gabonese" },
  { name: "Gambia", phonePrefix: "220", emoji: "🇬🇲", nationality: "Gambian" },
  {
    name: "Georgia",
    phonePrefix: "995",
    emoji: "🇬🇪",
    nationality: "Georgian",
  },
  { name: "Germany", phonePrefix: "49", emoji: "🇩🇪", nationality: "German" },
  { name: "Ghana", phonePrefix: "233", emoji: "🇬🇭", nationality: "Ghanaian" },
  { name: "Greece", phonePrefix: "30", emoji: "🇬🇷", nationality: "Greek" },
  {
    name: "Grenada",
    phonePrefix: "1-473",
    emoji: "🇬🇩",
    nationality: "Grenadian",
  },
  {
    name: "Guatemala",
    phonePrefix: "502",
    emoji: "🇬🇹",
    nationality: "Guatemalan",
  },
  { name: "Guinea", phonePrefix: "224", emoji: "🇬🇳", nationality: "Guinean" },
  {
    name: "Guinea-Bissau",
    phonePrefix: "245",
    emoji: "🇬🇼",
    nationality: "Bissau-Guinean",
  },
  { name: "Guyana", phonePrefix: "592", emoji: "🇬🇾", nationality: "Guyanese" },
  { name: "Haiti", phonePrefix: "509", emoji: "🇭🇹", nationality: "Haitian" },
  {
    name: "Honduras",
    phonePrefix: "504",
    emoji: "🇭🇳",
    nationality: "Honduran",
  },
  {
    name: "Hungary",
    phonePrefix: "36",
    emoji: "🇭🇺",
    nationality: "Hungarian",
  },
  {
    name: "Iceland",
    phonePrefix: "354",
    emoji: "🇮🇸",
    nationality: "Icelandic",
  },
  { name: "India", phonePrefix: "91", emoji: "🇮🇳", nationality: "Indian" },
  {
    name: "Indonesia",
    phonePrefix: "62",
    emoji: "🇮🇩",
    nationality: "Indonesian",
  },
  { name: "Iran", phonePrefix: "98", emoji: "🇮🇷", nationality: "Iranian" },
  { name: "Iraq", phonePrefix: "964", emoji: "🇮🇶", nationality: "Iraqi" },
  { name: "Ireland", phonePrefix: "353", emoji: "🇮🇪", nationality: "Irish" },
  { name: "Israel", phonePrefix: "972", emoji: "🇮🇱", nationality: "Israeli" },
  { name: "Italy", phonePrefix: "39", emoji: "🇮🇹", nationality: "Italian" },
  {
    name: "Ivory Coast",
    phonePrefix: "225",
    emoji: "🇨🇮",
    nationality: "Ivorian",
  },
  {
    name: "Jamaica",
    phonePrefix: "1-876",
    emoji: "🇯🇲",
    nationality: "Jamaican",
  },
  { name: "Japan", phonePrefix: "81", emoji: "🇯🇵", nationality: "Japanese" },
  {
    name: "Jordan",
    phonePrefix: "962",
    emoji: "🇯🇴",
    nationality: "Jordanian",
  },
  {
    name: "Kazakhstan",
    phonePrefix: "7",
    emoji: "🇰🇿",
    nationality: "Kazakhstani",
  },
  { name: "Kenya", phonePrefix: "254", emoji: "🇰🇪", nationality: "Kenyan" },
  {
    name: "Kiribati",
    phonePrefix: "686",
    emoji: "🇰🇮",
    nationality: "I-Kiribati",
  },
  {
    name: "Korea, North",
    phonePrefix: "850",
    emoji: "🇰🇵",
    nationality: "North Korean",
  },
  {
    name: "Korea, South",
    phonePrefix: "82",
    emoji: "🇰🇷",
    nationality: "South Korean",
  },
  { name: "Kosovo", phonePrefix: "383", emoji: "🇽🇰", nationality: "Kosovar" },
  { name: "Kuwait", phonePrefix: "965", emoji: "🇰🇼", nationality: "Kuwaiti" },
  {
    name: "Kyrgyzstan",
    phonePrefix: "996",
    emoji: "🇰🇬",
    nationality: "Kyrgyz",
  },
  { name: "Laos", phonePrefix: "856", emoji: "🇱🇦", nationality: "Lao" },
  { name: "Latvia", phonePrefix: "371", emoji: "🇱🇻", nationality: "Latvian" },
  {
    name: "Lebanon",
    phonePrefix: "961",
    emoji: "🇱🇧",
    nationality: "Lebanese",
  },
  { name: "Lesotho", phonePrefix: "266", emoji: "🇱🇸", nationality: "Basotho" },
  {
    name: "Liberia",
    phonePrefix: "231",
    emoji: "🇱🇷",
    nationality: "Liberian",
  },
  { name: "Libya", phonePrefix: "218", emoji: "🇱🇾", nationality: "Libyan" },
  {
    name: "Liechtenstein",
    phonePrefix: "423",
    emoji: "🇱🇮",
    nationality: "Liechtensteiner",
  },
  {
    name: "Lithuania",
    phonePrefix: "370",
    emoji: "🇱🇹",
    nationality: "Lithuanian",
  },
  {
    name: "Luxembourg",
    phonePrefix: "352",
    emoji: "🇱🇺",
    nationality: "Luxembourgish",
  },
  {
    name: "Madagascar",
    phonePrefix: "261",
    emoji: "🇲🇬",
    nationality: "Malagasy",
  },
  { name: "Malawi", phonePrefix: "265", emoji: "🇲🇼", nationality: "Malawian" },
  {
    name: "Malaysia",
    phonePrefix: "60",
    emoji: "🇲🇾",
    nationality: "Malaysian",
  },
  {
    name: "Maldives",
    phonePrefix: "960",
    emoji: "🇲🇻",
    nationality: "Maldivian",
  },
  { name: "Mali", phonePrefix: "223", emoji: "🇲🇱", nationality: "Malian" },
  { name: "Malta", phonePrefix: "356", emoji: "🇲🇹", nationality: "Maltese" },
  {
    name: "Marshall Islands",
    phonePrefix: "692",
    emoji: "🇲🇭",
    nationality: "Marshallese",
  },
  {
    name: "Mauritania",
    phonePrefix: "222",
    emoji: "🇲🇷",
    nationality: "Mauritanian",
  },
  {
    name: "Mauritius",
    phonePrefix: "230",
    emoji: "🇲🇺",
    nationality: "Mauritian",
  },
  { name: "Mexico", phonePrefix: "52", emoji: "🇲🇽", nationality: "Mexican" },
  {
    name: "Micronesia",
    phonePrefix: "691",
    emoji: "🇫🇲",
    nationality: "Micronesian",
  },
  {
    name: "Moldova",
    phonePrefix: "373",
    emoji: "🇲🇩",
    nationality: "Moldovan",
  },
  {
    name: "Monaco",
    phonePrefix: "377",
    emoji: "🇲🇨",
    nationality: "Monegasque",
  },
  {
    name: "Mongolia",
    phonePrefix: "976",
    emoji: "🇲🇳",
    nationality: "Mongolian",
  },
  {
    name: "Montenegro",
    phonePrefix: "382",
    emoji: "🇲🇪",
    nationality: "Montenegrin",
  },
  {
    name: "Morocco",
    phonePrefix: "212",
    emoji: "🇲🇦",
    nationality: "Moroccan",
  },
  {
    name: "Mozambique",
    phonePrefix: "258",
    emoji: "🇲🇿",
    nationality: "Mozambican",
  },
  { name: "Myanmar", phonePrefix: "95", emoji: "🇲🇲", nationality: "Burmese" },
  {
    name: "Namibia",
    phonePrefix: "264",
    emoji: "🇳🇦",
    nationality: "Namibian",
  },
  { name: "Nauru", phonePrefix: "674", emoji: "🇳🇷", nationality: "Nauruan" },
  { name: "Nepal", phonePrefix: "977", emoji: "🇳🇵", nationality: "Nepali" },
  {
    name: "Netherlands",
    phonePrefix: "31",
    emoji: "🇳🇱",
    nationality: "Dutch",
  },
  {
    name: "New Zealand",
    phonePrefix: "64",
    emoji: "🇳🇿",
    nationality: "New Zealander",
  },
  {
    name: "Nicaragua",
    phonePrefix: "505",
    emoji: "🇳🇮",
    nationality: "Nicaraguan",
  },
  { name: "Niger", phonePrefix: "227", emoji: "🇳🇪", nationality: "Nigerien" },
  {
    name: "Nigeria",
    phonePrefix: "234",
    emoji: "🇳🇬",
    nationality: "Nigerian",
  },
  {
    name: "North Macedonia",
    phonePrefix: "389",
    emoji: "🇲🇰",
    nationality: "Macedonian",
  },
  { name: "Norway", phonePrefix: "47", emoji: "🇳🇴", nationality: "Norwegian" },
  { name: "Oman", phonePrefix: "968", emoji: "🇴🇲", nationality: "Omani" },
  {
    name: "Pakistan",
    phonePrefix: "92",
    emoji: "🇵🇰",
    nationality: "Pakistani",
  },
  { name: "Palau", phonePrefix: "680", emoji: "🇵🇼", nationality: "Palauan" },
  {
    name: "Panama",
    phonePrefix: "507",
    emoji: "🇵🇦",
    nationality: "Panamanian",
  },
  {
    name: "Papua New Guinea",
    phonePrefix: "675",
    emoji: "🇵🇬",
    nationality: "Papua New Guinean",
  },
  {
    name: "Paraguay",
    phonePrefix: "595",
    emoji: "🇵🇾",
    nationality: "Paraguayan",
  },
  { name: "Peru", phonePrefix: "51", emoji: "🇵🇪", nationality: "Peruvian" },
  {
    name: "Philippines",
    phonePrefix: "63",
    emoji: "🇵🇭",
    nationality: "Filipino",
  },
  { name: "Poland", phonePrefix: "48", emoji: "🇵🇱", nationality: "Polish" },
  {
    name: "Portugal",
    phonePrefix: "351",
    emoji: "🇵🇹",
    nationality: "Portuguese",
  },
  { name: "Qatar", phonePrefix: "974", emoji: "🇶🇦", nationality: "Qatari" },
  { name: "Romania", phonePrefix: "40", emoji: "🇷🇴", nationality: "Romanian" },
  { name: "Russia", phonePrefix: "7", emoji: "🇷🇺", nationality: "Russian" },
  { name: "Rwanda", phonePrefix: "250", emoji: "🇷🇼", nationality: "Rwandan" },
  {
    name: "Saint Kitts and Nevis",
    phonePrefix: "1-869",
    emoji: "🇰🇳",
    nationality: "Kittitian or Nevisian",
  },
  {
    name: "Saint Lucia",
    phonePrefix: "1-758",
    emoji: "🇱🇨",
    nationality: "Saint Lucian",
  },
  {
    name: "Saint Vincent and the Grenadines",
    phonePrefix: "1-784",
    emoji: "🇻🇨",
    nationality: "Saint Vincentian",
  },
  { name: "Samoa", phonePrefix: "685", emoji: "🇼🇸", nationality: "Samoan" },
  {
    name: "San Marino",
    phonePrefix: "378",
    emoji: "🇸🇲",
    nationality: "Sammarinese",
  },
  {
    name: "Sao Tome and Principe",
    phonePrefix: "239",
    emoji: "🇸🇹",
    nationality: "São Toméan",
  },
  {
    name: "Saudi Arabia",
    phonePrefix: "966",
    emoji: "🇸🇦",
    nationality: "Saudi",
  },
  {
    name: "Senegal",
    phonePrefix: "221",
    emoji: "🇸🇳",
    nationality: "Senegalese",
  },
  { name: "Serbia", phonePrefix: "381", emoji: "🇷🇸", nationality: "Serbian" },
  {
    name: "Seychelles",
    phonePrefix: "248",
    emoji: "🇸🇨",
    nationality: "Seychellois",
  },
  {
    name: "Sierra Leone",
    phonePrefix: "232",
    emoji: "🇸🇱",
    nationality: "Sierra Leonean",
  },
  {
    name: "Singapore",
    phonePrefix: "65",
    emoji: "🇸🇬",
    nationality: "Singaporean",
  },
  { name: "Slovakia", phonePrefix: "421", emoji: "🇸🇰", nationality: "Slovak" },
  {
    name: "Slovenia",
    phonePrefix: "386",
    emoji: "🇸🇮",
    nationality: "Slovenian",
  },
  {
    name: "Solomon Islands",
    phonePrefix: "677",
    emoji: "🇸🇧",
    nationality: "Solomon Islander",
  },
  { name: "Somalia", phonePrefix: "252", emoji: "🇸🇴", nationality: "Somali" },
  {
    name: "South Africa",
    phonePrefix: "27",
    emoji: "🇿🇦",
    nationality: "South African",
  },
  {
    name: "South Sudan",
    phonePrefix: "211",
    emoji: "🇸🇸",
    nationality: "South Sudanese",
  },
  { name: "Spain", phonePrefix: "34", emoji: "🇪🇸", nationality: "Spanish" },
  {
    name: "Sri Lanka",
    phonePrefix: "94",
    emoji: "🇱🇰",
    nationality: "Sri Lankan",
  },
  { name: "Sudan", phonePrefix: "249", emoji: "🇸🇩", nationality: "Sudanese" },
  {
    name: "Suriname",
    phonePrefix: "597",
    emoji: "🇸🇷",
    nationality: "Surinamese",
  },
  { name: "Sweden", phonePrefix: "46", emoji: "🇸🇪", nationality: "Swedish" },
  {
    name: "Switzerland",
    phonePrefix: "41",
    emoji: "🇨🇭",
    nationality: "Swiss",
  },
  { name: "Syria", phonePrefix: "963", emoji: "🇸🇾", nationality: "Syrian" },
  {
    name: "Taiwan",
    phonePrefix: "886",
    emoji: "🇹🇼",
    nationality: "Taiwanese",
  },
  {
    name: "Tajikistan",
    phonePrefix: "992",
    emoji: "🇹🇯",
    nationality: "Tajikistani",
  },
  {
    name: "Tanzania",
    phonePrefix: "255",
    emoji: "🇹🇿",
    nationality: "Tanzanian",
  },
  { name: "Thailand", phonePrefix: "66", emoji: "🇹🇭", nationality: "Thai" },
  { name: "Togo", phonePrefix: "228", emoji: "🇹🇬", nationality: "Togolese" },
  { name: "Tonga", phonePrefix: "676", emoji: "🇹🇴", nationality: "Tongan" },
  {
    name: "Trinidad and Tobago",
    phonePrefix: "1-868",
    emoji: "🇹🇹",
    nationality: "Trinidadian or Tobagonian",
  },
  {
    name: "Tunisia",
    phonePrefix: "216",
    emoji: "🇹🇳",
    nationality: "Tunisian",
  },
  { name: "Turkey", phonePrefix: "90", emoji: "🇹🇷", nationality: "Turkish" },
  {
    name: "Turkmenistan",
    phonePrefix: "993",
    emoji: "🇹🇲",
    nationality: "Turkmen",
  },
  { name: "Tuvalu", phonePrefix: "688", emoji: "🇹🇻", nationality: "Tuvaluan" },
  { name: "Uganda", phonePrefix: "256", emoji: "🇺🇬", nationality: "Ugandan" },
  {
    name: "Ukraine",
    phonePrefix: "380",
    emoji: "🇺🇦",
    nationality: "Ukrainian",
  },
  {
    name: "United Arab Emirates",
    phonePrefix: "971",
    emoji: "🇦🇪",
    nationality: "Emirati",
  },
  {
    name: "United Kingdom",
    phonePrefix: "44",
    emoji: "🇬🇧",
    nationality: "British",
  },
  {
    name: "United States",
    phonePrefix: "1",
    emoji: "🇺🇸",
    nationality: "American",
  },
  {
    name: "Uruguay",
    phonePrefix: "598",
    emoji: "🇺🇾",
    nationality: "Uruguayan",
  },
  {
    name: "Uzbekistan",
    phonePrefix: "998",
    emoji: "🇺🇿",
    nationality: "Uzbekistani",
  },
  {
    name: "Vanuatu",
    phonePrefix: "678",
    emoji: "🇻🇺",
    nationality: "Ni-Vanuatu",
  },
  {
    name: "Vatican City",
    phonePrefix: "379",
    emoji: "🇻🇦",
    nationality: "Vatican",
  },
  {
    name: "Venezuela",
    phonePrefix: "58",
    emoji: "🇻🇪",
    nationality: "Venezuelan",
  },
  {
    name: "Vietnam",
    phonePrefix: "84",
    emoji: "🇻🇳",
    nationality: "Vietnamese",
  },
  { name: "Yemen", phonePrefix: "967", emoji: "🇾🇪", nationality: "Yemeni" },
  { name: "Zambia", phonePrefix: "260", emoji: "🇿🇲", nationality: "Zambian" },
  {
    name: "Zimbabwe",
    phonePrefix: "263",
    emoji: "🇿🇼",
    nationality: "Zimbabwean",
  },
];
